name: 'Generate release page'
description: 'Generate a release page'
inputs:
  package-name:
    description: Name of package
    required: true
  token:
    description: GH token
    required: true
    default: '${{ github.token }}'
  parent-dir:
    description: Parent directory of package
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
