name: deploy-nav
'on':
  push:
    branches:
      - main
    paths:
      - packages/nav/**
      - .github/workflows/deploy-nav.yml

defaults:
  run:
    working-directory: packages/nav

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Generate release page
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate release page
        uses: ./.github/actions/generate-release-page # Uses an action in the root directory
        with:
          token: '${{ secrets.ACTION_SECRET }}'
          package-name: 'nav'
          parent-dir: 'packages'
