on: [push]

jobs:
  show_context:
    runs-on: ubuntu-latest
    name: Show GitHub context
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
  hello_world_job:
    runs-on: ubuntu-latest
    name: Generate release page
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate release page
        uses: ./.github/actions/generate-release-page # Uses an action in the root directory
        with:
          token: '${{ secrets.ACTION_SECRET }}'
